// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6O5WfQpf-HiVIoLMm5-rLbOmZEWhr_RQ',
    appId: '1:126417928596:web:7167cf98a2e4666cf08f81',
    messagingSenderId: '126417928596',
    projectId: 'kunaigame-43516',
    authDomain: 'kunaigame-43516.firebaseapp.com',
    storageBucket: 'kunaigame-43516.appspot.com',
    measurementId: 'G-68M39DH40M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAljj5JDmjSN_xsw265PEaC9DKCTznqnQ',
    appId: '1:126417928596:android:5c0c12782b8b15b8f08f81',
    messagingSenderId: '126417928596',
    projectId: 'kunaigame-43516',
    storageBucket: 'kunaigame-43516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk8ARvcJILed9FI1Y0qva2ZC4DiUJgELg',
    appId: '1:126417928596:ios:e5a3577af0a4d38af08f81',
    messagingSenderId: '126417928596',
    projectId: 'kunaigame-43516',
    storageBucket: 'kunaigame-43516.appspot.com',
    iosClientId:
        '126417928596-hel1n0pkcd19h3j1h3mt95ojldoqmms8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk8ARvcJILed9FI1Y0qva2ZC4DiUJgELg',
    appId: '1:126417928596:ios:e5a3577af0a4d38af08f81',
    messagingSenderId: '126417928596',
    projectId: 'kunaigame-43516',
    storageBucket: 'kunaigame-43516.appspot.com',
    iosClientId:
        '126417928596-hel1n0pkcd19h3j1h3mt95ojldoqmms8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameTemplate',
  );
}
